// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("rescript/lib/js/curry.js");
var React = require("react");
var Electron = require("./lib/Electron.js");
var ConfigReader = require("./lib/ConfigReader.js");

var ipcRenderer = Electron.Electron.ipcRenderer;

function s(prim) {
  return prim;
}

function HardwareOverlay(Props) {
  var systemInfoStartValue = {
    cpu: 0.0,
    gpu: 0.0,
    memoryTotal: 0,
    memoryFree: 0,
    memoryPercentage: 0.0
  };
  var match = React.useState(function () {
        return systemInfoStartValue;
      });
  var setSystemInfo = match[1];
  var systemInfo = match[0];
  var match$1 = React.useState(function () {
        return "top-right";
      });
  var setContainerPos = match$1[1];
  var sendToIpcMain = function (param) {
    var response = ipcRenderer.sendSync("get-system-infos", null);
    return Curry._1(setSystemInfo, (function (param) {
                  return {
                          cpu: response.cpu,
                          gpu: response.gpu,
                          memoryTotal: response.memoryTotal,
                          memoryFree: response.memoryFree,
                          memoryPercentage: response.memoryPercentage
                        };
                }));
  };
  var mergeAndReadConfigFile = function (param) {
    ConfigReader.ConfigReader.mergeSettingsFile(undefined);
    var data = ConfigReader.ConfigReader.readSettingsFile(undefined);
    return Curry._1(setContainerPos, (function (param) {
                  return data.hardwareOverlayPos;
                }));
  };
  React.useEffect((function () {
          mergeAndReadConfigFile(undefined);
          setInterval(sendToIpcMain, 1500);
          
        }), []);
  return React.createElement("div", {
              className: "overlay-wrapper"
            }, React.createElement("div", {
                  className: "system-informations " + match$1[0]
                }, "Overlay", React.createElement("p", undefined, systemInfo.cpu.toFixed(1), "%"), React.createElement("p", undefined, systemInfo.gpu.toFixed(1), "%"), React.createElement("p", undefined, systemInfo.memoryPercentage.toFixed(1), "%")));
}

var make = HardwareOverlay;

exports.ipcRenderer = ipcRenderer;
exports.s = s;
exports.make = make;
/* react Not a pure module */
