// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var ReactDom = require("react-dom");
var HardwareOverlay = require("./HardwareOverlay.js");

function s(prim) {
  return prim;
}

function Index$App(Props) {
  return React.createElement(HardwareOverlay.make, {});
}

var App = {
  make: Index$App
};

var root = document.querySelector("#root");

if (!(root == null)) {
  ReactDom.render(React.createElement("div", undefined, React.createElement(Index$App, {})), root);
}

exports.s = s;
exports.App = App;
/* root Not a pure module */
