// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Electron = require("electron");

var ipcRenderer = Electron.ipcRenderer;

var Electron$1 = {
  ipcRenderer: ipcRenderer
};

exports.Electron = Electron$1;
/* ipcRenderer Not a pure module */
