// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Fs = require("fs");

function existsSync(prim) {
  return Fs.existsSync(prim);
}

function readFileSync(prim) {
  return Fs.readFileSync(prim);
}

function writeFileSync(prim0, prim1) {
  Fs.writeFileSync(prim0, prim1);
  
}

function mkdirSync(prim) {
  Fs.mkdirSync(prim);
  
}

function toString(prim) {
  return String.toString(prim);
}

var FileSystem = {
  existsSync: existsSync,
  readFileSync: readFileSync,
  writeFileSync: writeFileSync,
  mkdirSync: mkdirSync,
  toString: toString
};

exports.FileSystem = FileSystem;
/* fs Not a pure module */
