// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';


function stringify(prim) {
  return JSON.stringify(prim);
}

function parse(prim) {
  return JSON.parse(prim);
}

var $$JSON$1 = {
  stringify: stringify,
  parse: parse
};

exports.$$JSON = $$JSON$1;
/* No side effect */
